---
#
#
#
- name: "Docker | Installing packages"
  apt:
     name: docker-ce
     state: present
  tags:
     - docker
     - bootstrap

- name: "Docker | Start and Enable docker service"
  service:
     name: docker
     state: started
     enabled: yes
  tags:
     - docker
     - bootstrap


